name: Auto Deploy

on:
  push:
    branches:
      - test/deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - uses: pnpm/action-setup@v2
        with:
          version: 7.24.3

      - name: Build
        run: pnpm build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: .vuepress/dist

      - name: Deploy
        uses: actions/deploy-pages@v1
